#include <stdio.h>
#include <stdlib.h>
#include <time.h>

// 3276741
int main()
{
    printf("%d to %d", 0, RAND_MAX);  //maximum value generated by rand.

    srand(time(NULL));
    printf("%d\n", rand());
    printf("%d\n", rand());
    printf("%d\n", rand());
    printf("%d\n", rand());
    printf("%d\n", rand());
    printf("%d\n", rand());




    return 0;
}